theme: jekyll-theme-cayman
title:        Школа Глубокого Обучения
tagline:      МФТИ
author:
  name:       "dlphystech@gmail.com"
  url:        mailto:dlphystech@gmail.com
vk:
  name:       vk.com/dlschlmipt
  url:        https://vk.com/dlschlmipt
